document.write("<p>A large remote-controlled mechanized sphere")
document.write("A large remote-controlled mechanized sphere")
document.write("A large remote-controlled mechanized sphere")
document.write("A large remote-controlled mechanized sphere")
document.write("A large remote-controlled mechanized sphere</p>")
